# Generated by Django 3.2.16 on 2022-11-19 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Пол')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Фамилия')),
                ('maiden_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Девичья фамилия')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('lived_ca', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Годы жизни (приблизительно)')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='people', verbose_name='Фото члена семьи')),
                ('tree_owner', models.BooleanField(default=False, verbose_name='Исходный член семьи')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_father', to='people.person', verbose_name='Отец')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_mother', to='people.person', verbose_name='Мать')),
                ('spouse', models.ManyToManyField(blank=True, related_name='_people_person_spouse_+', to='people.Person', verbose_name='Супруг/Супруга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Член семьи',
                'verbose_name_plural': 'Семья',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Описание фотографии')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image file')),
                ('persons', models.ManyToManyField(blank=True, related_name='imgs', to='people.Person', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание документа')),
                ('doc', models.ImageField(blank=True, null=True, upload_to='documents', verbose_name='Document file')),
                ('persons', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
