# Generated by Django 3.2.16 on 2022-11-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='persons',
            new_name='person',
        ),
    ]
