# Generated by Django 3.2.16 on 2022-11-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20221120_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, verbose_name='Описание документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.ImageField(blank=True, default='', upload_to='documents', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='document',
            name='person',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='Владелец документа'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='', max_length=300, verbose_name='Описание фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='images', verbose_name='Image file'),
        ),
        migrations.AlterField(
            model_name='image',
            name='persons',
            field=models.ManyToManyField(blank=True, default='', related_name='imgs', to='people.Person', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lived_ca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Годы жизни (приблизительно)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='maiden_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Девичья фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='people', verbose_name='Фото члена семьи'),
        ),
    ]
